### PR TITLE
Add 2 sentences to configure option by name in settings menus

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by guewen** [comment]
I fear duplicates with these phrases.
What do you think of something more specific, such as:

```
I set "{option}" to "{value}" in the settings menu "{menu}"'

I {action} "{option}" in the settings menu "{menu}"
```

**Comment by yvaucher** [comment]
@guewen it works with one of our projects that way. For duplication isn't there a priority base on first match in definition?

**Comment by yvaucher** [comment]
I don't get the issue about duplicates?

**Comment by guewen** [comment]
@yvaucher no issue within this steps library. But when using only a few words in a phrase, risks of collisions are high and as this commit is in the main library, IMO we should care not to introduce too general meaning sentences.

**Comment by guewen** [comment]
@yvaucher I already issued this problem several times that's why I raise the point

**Comment by yvaucher** [comment]
@guewen I added menu at the end, it keeps the sentence near what it is and saying `in the "Accounting" settings menu` seems correct english to me. correct me if I'm wrong.

**Comment by gurneyalex** [comment]
:+1:

**Comment by guewen** [comment]
Thanks. Yes indeed `in the "Accounting" settings menu` is correct. Still you expect `in "Accounting" settings menu` without the `the` article which does not seem correct to me, but I may be wrong.

**Comment by nbessi** [comment]
Hmm if we want to introduce this sentence in DSL we may want to support non flat value like sequence setting, default taxes etc.

**Comment by guewen** [comment]
:+1:

**Pull request merged**
