### PR TITLE
try to avoid ascii codec decode error on message

### PR DESCRIPTION
**Pull request by charbeljc**

### CODE REVIEW

**Comment by charbeljc** [comment]
Redoing #28, as suggested by @lepistone

**Comment by lepistone** [comment]
I see that we need to be able to read error messages in all cases.

At some point we'll surely do a review of `behave_better` to see if the monkey-patches it does are still needed (they might be included in behave upstrea).

So here and now, :+1: thanks!

**Comment by guewen** [comment]
Thanks

**Comment by lepistone** [comment]
I investigated a bit more, and the problem is actually in the `indent` method in `behave` <= 1.2.4 itself:

https://github.com/behave/behave/blob/v1.2.4/behave/textutil.py#L29

Here `unicode` is called with no arguments, which uses ASCII. They should probably `errors='replace'`.
In behave 1.2.5 they are using `six` for supporting python 2 and 3. It might work already, and needs a test on their side. I'll give it a try.

**Comment by lepistone** [comment]
and there is https://github.com/behave/behave/pull/258

**Comment by lepistone** [comment]
A bit more investigation: the case I have in a customer project is `load()` that fails and outputs the failing query, and the query contains non-ascii characters. Even with this workaround, the line above in behave 1.2.4 still crashes and the failing query is not shown. Bumping to behave 1.2.5 needs some adaptation in the `behave_better` monkey-patches. Stay tuned...

**Pull request merged**
