### PR TITLE
[IMP] add new phrase to be able to configure apps in V9

### PR DESCRIPTION
**Pull request by damdam-s**
now phrase like 'Given I set "Addresses" to "Display 3 fields on
    sales orders: customer, invoice address, delivery address" in
    "base.menu_sale_general_settings" settings menu by xml_id' can be processed

### CODE REVIEW

**Comment by lepistone** [comment]
:+1: thanks

**Comment by yvaucher** [comment]
Don't we want something closer to the 8.0 version ? As now settings are splitted in all topics.

Couldn't we use the full path ? Like Sales/Configuration/Settings

The idea is to be not too technical. Otherwise we wouldn't make phrases

**Comment by damdam-s** [comment]
@yvaucher yes of course and that's why I added `by xml_id` in the phrase. I needed to do it quickly. 
I agree with you in the fact that it shouldn't have to be too technical ...

**Comment by yvaucher** [comment]
Superseeded by #49

**Pull request closed without merging**
