### PR TITLE
[FIX] missing 'import time' statement

### PR DESCRIPTION
**Pull request by damdam-s**

### CODE REVIEW

**Comment by vrenaville** [comment]
:+1:

**Comment by charbeljc** [comment]
:+1:

**Comment by guewen** [comment]
@damdam-s is there a reason not to import it top-level of the module?

**Comment by damdam-s** [comment]
@guewen no particular reason. I asked myself the question and as it's a single use of `time`, I put the import here instead of the top.
I can change if you want

**Comment by damdam-s** [comment]
updated.
import changed

**Comment by guewen** [comment]
Thanks :+1:

**Pull request merged**
